# ---------------- #
#    网站核心设置    #
# ---------------- #

# 网站的标题，会显示在浏览器标签页和主页大标题上
title: A LEAF 

description: >-
  个人学习记录~

# 网站的永久链接格式，/:slug 表示文章的网址会是 "域名/文件名"，很简洁，建议保留
permalink: /:slug

# 网站的小图标，您可以将自己的 logo.png 放在仓库根目录，或者暂时删除这行
favicon: "./logo.png"


# ---------------- #
#      主题设置      #
# ---------------- #

# 指定使用 moonwalk 主题
remote_theme: abhinavs/moonwalk

# 主题的具体配置
theme_config:
  # 外观设置
  appearance: "dark" # 默认外观可以是 "light" (亮色), "dark" (暗黑) 或 "auto" (跟随系统)
  appearance_toggle: true # 是否允许用户在右上角切换亮色/暗黑模式

  # 文章页面返回主页的链接文字
  back_home_text: "返回主页" # <-- 您可以修改成 "Home" 或其他

  # 日期格式
  date_format: "%Y-%m-%d" # 年-月-日

  # --- 主页布局控制 ---
  show_description: true # 在主页标题下显示网站描述
  show_navbar: true      # 显示顶部的导航栏 (链接在 _data/home.yml 中修改)
  show_footer: true      # 显示底部的页脚链接 (链接在 _data/home.yml 中修改)
  show_copyright: true   # 在页脚显示版权信息

  # 下面这些是控制主页显示不同“卡片”区域的开关，我们先只保留博客文章列表
  show_projects: false      # 不显示“项目”卡片
  show_blog: true           # **关键：显示 _posts 文件夹里的文章列表**
  show_old_projects: false  # 不显示“旧项目”卡片
  show_misc_list: false     # 不显示“杂项”列表

  # --- 文章页面设置 ---
  show_reading_time: true # 在文章顶部显示阅读时间和字数
  show_tags: true # 在文章底部显示标签（需要在文章的 Front Matter 中设置 tags）

  # 主页上不同区域的标题文字
  home:
    title_blog: "最新笔记" # <-- 修改文章列表的标题

# ==============================
#      分页设置 (在此处添加)
# ==============================
paginate: 5 # 每页显示5篇文章，您可以改成任何您想要的数字
paginate_path: "/page:num/" # 分页的网址格式，例如 yoursite.com/page2/


# ---------------- #
#  Jekyll 核心设置  #
# ---------------- #

# 语法高亮工具
highlighter: rouge

#开启latex
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax

# Sass (CSS预处理器) 的设置
sass:
  style: :compressed

# Jekyll 插件列表，这些是主题正常运行所必需的，请勿改动
plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag